apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cxf5j027v-go 
  janus-idp.io/tekton: cxf5j027v-go
  backstage.io/kubernetes-id: cxf5j027v-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cxf5j027v-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml